name: 'Install Mamba'
description: 'Install Mamba'
inputs:
  installer-url:
    description: 'Installer URL'
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash -l -e -x {0}
      run: |
        if [ ! -e ${HOME}/bin/micromamba ]; then
          echo "Downloading ${{inputs.installer-url}}"
          curl --retry 5 -Lfs "${{ inputs.installer-url }}" | tar -xvj -C ${HOME}/ bin/micromamba
        fi
        if ! command -vp micromamba >/dev/null 2>&1 ; then
          echo "Adding micromamba init to bash profile"
          echo "$(~/bin/micromamba shell hook -s posix)" >> ${HOME}/.bash_profile
        fi
