name: 'Download meta.yaml'
description: 'Download meta.yaml from the conda-forge GK feedstock'
runs:
  using: "composite"
  steps:
    - shell: bash -l -e {0}
      run: |
        set -x
        mkdir -p conda-recipe
        curl -s -L -o conda-recipe/meta.yaml https://raw.githubusercontent.com/conda-forge/genomekit-feedstock/main/recipe/meta.yaml
        # build from local source, not from the latest release tarball
        sed -i -e 's|url: https://github.com/deepgenomics/GenomeKit/archive/refs/tags/v.*$|path: ../|1; /sha256: /d' conda-recipe/meta.yaml
        sed -i -e 's|python -m unittest discover|python -m unittest tests.test_apply_variants tests.test_genome tests.test_genome_annotation tests.test_genome_dna tests.test_genome_track tests.test_gk_data tests.test_interval tests.test_read_alignments tests.test_serialize tests.test_twobitutils tests.test_variant tests.test_variant_genome tests.test_variant_table -v -b|1' conda-recipe/meta.yaml
        cat conda-recipe/meta.yaml
        set +x
