name: 'Download meta.yaml'
description: 'Download meta.yaml from the conda-forge GK feedstock'
runs:
  using: "composite"
  steps:
    - shell: bash -l -e {0}
      run: |
        set -x
        mkdir -p conda-recipe
        curl -s -L -o conda-recipe/meta.yaml https://raw.githubusercontent.com/conda-forge/genomekit-feedstock/main/recipe/meta.yaml
        export GK_VERSION=$(grep "version = " setup.py | awk -F'"' '{print $2}')
        # - replace the (non-existent) tarball with local path
        # - remove the related sha for that tarball
        # - build for all locally allowed versions of python (conda-recipe/conda_build_config.yaml)
        # - set the version to the local release-please version (for docs and docker publish)
        sed -E "s|url: https://github.com/deepgenomics/GenomeKit/archive/refs/tags/v.*$|path: ../|1; /sha256: /d; /skip: true /d;s/\{% set version = \"[0-9]+\.[0-9]+\.[0-9]+\" %\}/{% set version = \"${GK_VERSION}\" %}/" conda-recipe/meta.yaml
        head -10 conda-recipe/meta.yaml
        set +x
