name: 'Configure Conda'
description: 'Configure Conda'
inputs:
  env:
    description: 'Environment name'
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash -l -e {0}
      run: |
        source ${HOME}/.bash_profile # for macos
        set -x
        if [ ! -e "${HOME}/.condarc" ]; then
          micromamba activate ${{ inputs.env }}
          conda config --set always_yes yes --set changeps1 no --set auto_update_conda no --set channel_priority flexible
          # cache additional pkgs separately from docker pre-install
          conda config --prepend pkgs_dirs ${HOME}/micromamba/envs/${{ inputs.env }}/pkgs
          # fallback to docker pre-installed packages
          conda config --append pkgs_dirs ${HOME}/micromamba/pkgs
          conda config --prepend channels conda-forge
        fi
        set +x
