version: 2

yaml-anchors:
  on-any-push: &on-any-push
    filters:
      branches:
        ignore: /^release-please.*/

commands:
  restore_mamba_env:
    steps:
      - restore_cache:
          # TODO: download meta.yaml from the conda-forge repo
          keys:
            - mamba-env-{{ arch }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "conda-recipe/meta.yaml" }}

  save_mamba_env:
    steps:
      - save_cache:
          key: mamba-env-{{ arch }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "conda-recipe/meta.yaml" }}
          paths:
            - ~/micromamba
            - ~/.condarc
            - ~/bin/micromamba

  resolve_tilde:
    description: Resolve ~ inside environment variables
    steps:
      - run:
          command: |
            echo 'export CIRCLE_WORKING_DIRECTORY="${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}"' >> $BASH_ENV

  install_mamba:
    description: Install Mamba
    steps:
      - run:
          command: |
            if [ ! -e ~/bin/micromamba ]; then
              curl --retry 5 -Lfs ${CONDA_INSTALLER} | tar -xvj -C ~/ bin/micromamba
            fi
            if ! command -vp micromamba >/dev/null 2>&1 ; then
              echo "$(~/bin/micromamba shell hook -s posix)" >> ${BASH_ENV}
            fi

  configure_conda:
    description: Configure conda
    parameters:
      env:
        type: string
    steps:
      - run:
          command: |
            if [ ! -e "${HOME}/.condarc" ]; then
              micromamba activate << parameters.env >>
              conda config --set always_yes yes --set changeps1 no --set auto_update_conda no
              # cache additional pkgs separately from docker pre-install
              conda config --prepend pkgs_dirs ~/micromamba/envs/<< parameters.env >>/pkgs
              # fallback to docker pre-installed packages
              conda config --append pkgs_dirs ~/micromamba/pkgs
              conda config --prepend channels conda-forge
            fi

  build:
    steps:
      - checkout
      - restore_mamba_env
      - resolve_tilde
      - install_mamba
      - run:
          command: |
            if [ ! -d "${HOME}/micromamba/envs/build" ]; then
              micromamba create -yqn build -c conda-forge \
                boa==0.16.0 mamba==1.5.7 conda==24.1.2 \
                ccache
            fi
          name: Create conda environment
      - configure_conda:
            env: build
      - restore_cache:
          keys:
            - gk-mamba-ccache-{{ arch }}-{{ .Branch }}-{{ .Revision }}
      - run:
          command: |
            micromamba activate build
            ccache -M 100M
      - run:
          command: |
            micromamba activate build
            mkdir ~/conda-bld
            conda mambabuild --croot ~/conda-bld -q --no-test conda-recipe
            conda build --croot ~/conda-bld purge
            conda clean -it
          name: Build conda packages
      - save_mamba_env:
      - persist_to_workspace:
          paths:
            - conda-bld/*/*.tar.bz2
          root: ~/

  test:
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - resolve_tilde
      - run:
          command: echo "export TEST_RESULTS=${HOME}/test-results/${PLATFORM}" >> ${BASH_ENV}
      - run:
          command: |
            cat > .circleci/.coveragerc << 'EOL'
            [run]
            branch = True
            relative_files = True
            source = genome_kit
            EOL
          name: Generate .circleci/.coveragerc
      - run:
          command: |
            cat > .circleci/run_cov_tests.sh << 'EOL'
            # prevent absolute test imports from walking up to the project source
            cp -rf ${CIRCLE_WORKING_DIRECTORY}/tests .
            COVERAGE_FILE=${TEST_RESULTS}/.coverage.${CIRCLE_NODE_INDEX} \
              coverage run --rcfile=${CIRCLE_WORKING_DIRECTORY}/.circleci/.coveragerc \
              -m pytest -x -ra \
              --junit-xml=${TEST_RESULTS}/test-results.xml -o junit_family=xunit1 \
              tests $@
            EOL
            cat > .circleci/run_cov_splitted_tests.sh << 'EOL'
            # prevent absolute test imports from walking up to the project source
            cp -rf ${CIRCLE_WORKING_DIRECTORY}/tests .
            TEST_FILES=$(circleci tests glob "tests/**/test_*.py" | circleci tests split --split-by=timings)
            echo ${TEST_FILES}
            # if there are less than 4 tests, the other executors will run all tests
            # therefore, we check if there are tests to run on the executor
            if ! [[ -z $TEST_FILES ]] ; then
              COVERAGE_FILE=${TEST_RESULTS}/.coverage.${CIRCLE_NODE_INDEX} \
                coverage run --rcfile=${CIRCLE_WORKING_DIRECTORY}/.circleci/.coveragerc \
                -m pytest -x -ra \
                --junit-xml=${TEST_RESULTS}/test-results.xml -o junit_family=xunit1 \
                ${TEST_FILES} $@
            fi
            EOL
          name: Generate the test scripts
      - restore_mamba_env
      - install_mamba
      - run:
          command: |
            if [ ! -d "${HOME}/micromamba/envs/test" ]; then
              micromamba create -yqn test -c conda-forge \
                boa==0.16.0 mamba==1.5.7 conda==24.1.2 coverage
            fi
          name: Create conda environment
      - configure_conda:
            env: test
      - run:
          command: |
            micromamba activate test
            mkdir -p ${TEST_RESULTS}
            export PYTHONUNBUFFERED=1
            conda index ~/conda-bld
            # filter the configuration by the container
            # see https://circleci.com/docs/2.0/parallelism-faster-jobs/#using-environment-variables-to-split-tests
            case ${CIRCLE_NODE_INDEX} in
              0)
                conda mambabuild --croot /tmp/conda-bld -t ~/conda-bld/*/*py38*.tar.bz2 --extra-deps python=3.8
                ;;
              1)
                conda mambabuild --croot /tmp/conda-bld -t ~/conda-bld/*/*py39*.tar.bz2 --extra-deps python=3.9
                ;;
              2)
                conda mambabuild --croot /tmp/conda-bld -t ~/conda-bld/*/*py310*.tar.bz2 --extra-deps python=3.10
                ;;
            esac
            conda clean -it
          name: Test conda packages
          no_output_timeout: 10m
      - save_mamba_env:
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          destination: test-results
          path: ~/test-results
      - run:
          command: |
            if [ -n "$(ls -A ~/test-results/*/.coverage.* 2>/dev/null)" ]
            then
            :
            else
              circleci-agent step halt
            fi
          name: Halt if no test results
      - persist_to_workspace:
          paths:
            - test-results/*/.coverage*
          root: ~/

jobs:

  build-linux:
    docker:
      - image: cimg/base:stable
    resource_class: large
    working_directory: ~/project
    steps:
      - build
    environment:
      CONDA_INSTALLER: https://micro.mamba.pm/api/micromamba/linux-64/1.5.7
      PLATFORM: linux

  build-macos:
    macos:
      xcode: 14.2.0
    resource_class: macos.x86.medium.gen2
    steps:
      - build
      - save_cache:
          key: gk-mamba-ccache-{{ arch }}-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/.ccache
    environment:
      CONDA_INSTALLER: https://micro.mamba.pm/api/micromamba/osx-64/1.5.7
      MACOSX_DEPLOYMENT_TARGET: 10.15
      PLATFORM: osx

  test-linux:
    docker:
      - image: cimg/base:stable
    resource_class: medium
    working_directory: ~/project
    environment:
      CONDA_INSTALLER: https://micro.mamba.pm/api/micromamba/linux-64/1.5.7
      PLATFORM: linux
      COVER_MODULE: genome_kit
    parallelism: 1
    steps:
      - test

  test-macos:
    macos:
      xcode: 14.2.0
    resource_class: macos.x86.medium.gen2
    environment:
      CONDA_INSTALLER: https://micro.mamba.pm/api/micromamba/linux-64/1.5.7
      MACOSX_DEPLOYMENT_TARGET: 10.15
      PLATFORM: osx
      COVER_MODULE: genome_kit
    parallelism: 1
    steps:
      - test

  deploy-coverage:
    docker:
      - image: cimg/base:stable
    resource_class: medium
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/
      - run:
          command: |
            if [ -n "$(ls -A ~/test-results/*/.coverage.* 2>/dev/null)" ]
            then
            :
            else
              circleci-agent step halt
            fi
          name: Halt if no test results
      - checkout
      - restore_mamba_env
      - install_mamba
      - run:
          command: |
            micromamba create -yqn coverage -c conda-forge coverage
          name: Create conda environment
      - resolve_tilde
      - run:
          command: |
            echo "[paths]" >> .coveragerc
            echo "source =" >> .coveragerc
            echo "  genome_kit" >> .coveragerc
            echo "  */site-packages/genome_kit" >> .coveragerc
            echo "  */site-packages/*/genome_kit" >> .coveragerc
            micromamba activate coverage
            coverage combine ~/test-results/*/.coverage.*
          name: Consolidate test coverage into a single report
      - run:
          command: |
            micromamba activate coverage
            coverage report -i
            coverage html -i -d ~/test-results/htmlcov
          name: Report coverage
      - store_artifacts:
          destination: test-results/htmlcov
          path: ~/test-results/htmlcov
    environment:
      CONDA_INSTALLER: https://micro.mamba.pm/api/micromamba/linux-64/1.5.7
      PLATFORM: linux


workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-linux:
          <<: *on-any-push
      - build-macos:
          <<: *on-any-push
      - test-linux:
          <<: *on-any-push
          requires:
            - build-linux
      - test-macos:
          <<: *on-any-push
          requires:
            - build-macos
      - deploy-coverage:
          <<: *on-any-push
          requires:
            - test-linux
            - test-macos
