name: 'build gk'
description: 'Build GenomeKit conda package and save it under ~/conda-bld'
inputs:
  platform:
    description: 'platform name used in the mamba installer url'
    required: true
runs:
  using: "composite"
  steps:
    - name: get meta.yaml from conda-forge
      uses: ./.github/actions/curl-meta-yaml

    - name: try to restore the mamba env
      id: restore_mamba_cache
      uses: actions/cache/restore@v4
      with:
        key: mamba-env-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('.github/workflows/run-tests.yaml', '.github/actions/**') }}
        path: |
          ~/micromamba
          ~/.condarc
          ~/bin/micromamba

    - name: try to restore the gk package tarballs
      id: restore_gk_pkg
      uses: actions/cache/restore@v4
      with:
        key: mamba-env-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('.github/workflows/run-tests.yaml', '.github/actions/**', 'conda-recipe/meta.yaml', 'src/**', 'genome_kit/**') }}
        path: |
          ~/conda-bld

    - name: install mamba
      uses: ./.github/actions/install-mamba
      with:
        installer-url: https://micro.mamba.pm/api/micromamba/${{ inputs.platform }}/1.5.7

    - name: create build env
      shell: bash -l -e {0}
      run: |
        set -x
        if [ ! -d "${HOME}/micromamba/envs/build" ]; then
          micromamba create -yqn build -c conda-forge \
            boa==0.16.0 mamba==1.5.7 conda==24.1.2 \
            ccache
        fi
        set +x

    - if: ${{ steps.restore_mamba_cache.outputs.cache-hit != 'true' }}
      uses: ./.github/actions/configure-conda
      with:
        env: build

    - name: save mamba gk ccache
      id: save_mamba_gk_ccache
      uses: actions/cache@v4
      with:
        key: gk-mamba-ccache-${{ runner.os }}-${{ runner.arch }}-${{ github.head_ref || github.ref_name }}-${{ github.sha }}
        restore-keys: |
          gk-mamba-ccache-${{ runner.os }}-${{ runner.arch }}-${{ github.head_ref || github.ref_name }}
          gk-mamba-ccache-${{ runner.os }}-${{ runner.arch }}-
        path: |
          ~/.ccache

    - name: set compiler cache size
      shell: bash -l -e {0}
      run: |
        set -x
        micromamba activate build
        ccache -M 100M
        mkdir -p ~/.ccache
        set +x

    - if: ${{ steps.restore_gk_pkg.outputs.cache-hit != 'true' }}
      name: build conda package
      shell: bash -l -e {0}
      run: |
        set -x
        micromamba activate build
        mkdir ~/conda-bld
        conda mambabuild --croot ~/conda-bld -q --no-test conda-recipe
        conda build --croot ~/conda-bld purge
        conda clean -it

    - name: cache mamba env
      id: save_mamba_cache
      uses: actions/cache/save@v4
      with:
        key: mamba-env-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('.github/workflows/run-tests.yaml', '.github/actions/**') }}
        path: |
          ~/micromamba
          ~/.condarc
          ~/bin/micromamba

    - name: cache gk package tarballs
      id: save_gk_pkg
      uses: actions/cache/save@v4
      with:
        key: mamba-env-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('.github/workflows/run-tests.yaml', '.github/actions/**', 'conda-recipe/meta.yaml', 'src/**', 'genome_kit/**') }}
        path: |
          ~/conda-bld
