name: 'Parallel Run Unittests'
description: 'Run unittests for one version of python'
inputs:
  py-version-long:
    description: 'long-form python version (e.g 3.10)'
    required: true
  py-version-short:
    description: 'short-form python version (e.g 310)'
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash -l -e {0}
      run: |
        set -x
        micromamba activate test
        # TODO remove? https://docs.python.org/3/using/cmdline.html#cmdoption-u now says:
        # "Changed in version 3.7: The text layer of the stdout and stderr streams now is unbuffered."
        export PYTHONUNBUFFERED=1 
        conda index ~/conda-bld
        conda mambabuild --croot /tmp/conda-bld -t ~/conda-bld/*/*py${{ inputs.py-version-short }}*.tar.bz2 --extra-deps python=${{ inputs.py-version-long }}
        conda clean -it
        set +x
