name: 'Create Conda Env'
description: 'Create Conda Env'
runs:
  using: "composite"
  steps:
    - shell: bash -l -e {0}
      run: |
        set -x
        if [ ! -d "${HOME}/micromamba/envs/build" ]; then
          micromamba create -yqn build -c conda-forge \
            boa==0.16.0 mamba==1.5.7 conda==24.1.2 \
            ccache
        fi
        set +x
