name: 'Download meta.yaml (Windows)'
description: 'Download meta.yaml from the conda-forge GK feedstock on Windows'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        # Fail if on main branch and conda-recipe/meta.yaml exists
        if [[ "${GITHUB_REF_NAME}" == "main" && -f "conda-recipe/meta.yaml" ]]; then
          echo "ERROR: conda-recipe/meta.yaml should not be committed to main. Failing build."
          exit 1
        fi

        set -euxo pipefail
        mkdir -p conda-recipe

        # If meta.yaml exists, use it (to allow quick iteration in feature branches)
        if [[ -f "conda-recipe/meta.yaml" ]]; then
          echo "WARN: Using existing conda-recipe/meta.yaml"
        else
          curl -s -L -o conda-recipe/meta.yaml https://raw.githubusercontent.com/conda-forge/genomekit-feedstock/main/recipe/meta.yaml
        fi

        export GK_VERSION=$(grep "version = " setup.py | awk -F'"' '{print $2}')

        # sed on Git Bash (Windows) uses GNU sed syntax
        sed -i "s|url: https://github.com/deepgenomics/GenomeKit/archive/refs/tags/v.*$|path: ../|1" conda-recipe/meta.yaml
        sed -i "/sha256: /d" conda-recipe/meta.yaml
        sed -i "/skip: true /d" conda-recipe/meta.yaml
        sed -i "s/{% set version = \"[^\"]*\" %}/{% set version = \"${GK_VERSION}\" %}/" conda-recipe/meta.yaml

        head -10 conda-recipe/meta.yaml
