name: 'Configure Conda (Windows)'
description: 'Configure Conda on Windows'
inputs:
  env:
    description: 'Environment name'
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        set -euxo pipefail
        if [ ! -e "$USERPROFILE/.condarc" ]; then
          micromamba run -n ${{ inputs.env }} conda config --set always_yes yes --set changeps1 no --set auto_update_conda no
          micromamba run -n ${{ inputs.env }} conda config --prepend pkgs_dirs "$MAMBA_ROOT_PREFIX/envs/${{ inputs.env }}/pkgs"
          micromamba run -n ${{ inputs.env }} conda config --append pkgs_dirs "$MAMBA_ROOT_PREFIX/pkgs"
          micromamba run -n ${{ inputs.env }} conda config --prepend channels conda-forge
        fi
