name: build-wheels
run-name: build-wheels

on:
  push:
    branches: ["test-build-macos-wheel"]
#    tags: [ "v*" ]
    paths:
    - ".github/actions/**"
    - ".github/workflows/**"
    - "conda-recipe/**"
    - "genome_kit/**"
    - "setup.py"
    - "pyproject.toml"
    - "setup/**"
    - "src/**"
    - "tests/**"

jobs:
#  build-wheel-linux:
#    strategy:
#      matrix:
#        include:
#          - arch_name: x86_64
#            build_image: quay.io/pypa/manylinux_2_28_x86_64
#            runner: ubuntu-latest
#          - arch_name: aarch64
#            build_image: quay.io/pypa/manylinux_2_28_aarch64
#            runner: ubuntu-24.04-arm
#
#    runs-on: ${{ matrix.runner }}
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Build and repair wheels for Python 3.9–3.12 (${{ inputs.arch_name }})
#        run: |
#          docker run --rm -v $(pwd):/io -e GK_BUILD_WHEELS=1 ${{ inputs.build_image }} /bin/bash -c "
#            set -euxo pipefail
#            cd /io
#            mkdir -p wheels
#
#            PYTHONS=(
#              /opt/python/cp39-cp39/bin/python
#              /opt/python/cp310-cp310/bin/python
#              /opt/python/cp311-cp311/bin/python
#              /opt/python/cp312-cp312/bin/python
#            )
#
#            for PYTHON in \${PYTHONS[@]}; do
#              \$PYTHON -m pip install -U pip setuptools wheel cmake auditwheel \"numpy==2\"
#              rm -rf build dist *.egg-info
#              \$PYTHON setup.py bdist_wheel
#              cp dist/*.whl wheels/
#            done
#          "
#
#      - name: Test wheels across Python 3.9–3.12 (${{ inputs.arch_name }})
#        run: |
#          set -euxo pipefail
#
#          for PYVER in 3.9 3.10 3.11 3.12; do
#            TAG="cp${PYVER/./}"
#
#            echo "Testing on Python $PYVER (${{ inputs.arch_name }}) with tag $TAG"
#
#            docker run --rm \
#              -v $(pwd)/wheels:/wheels \
#              -v $(pwd)/tests:/tests \
#              python:$PYVER-slim /bin/bash -c "
#                set -euxo pipefail
#                apt-get update && apt-get install -y gcc python3-dev
#                python -m pip install --upgrade pip
#                WHEEL=\$(ls /wheels/*${TAG}*.whl | head -n 1)
#                echo 'Installing wheel: ' \$WHEEL
#                python -m pip install \$WHEEL
#                python -c 'import genome_kit; print(genome_kit.__version__)'
#                ls /tests/test_*.py | sed 's/\.py$//' | sed 's/\/tests\//tests./' | CI=1 xargs --verbose -I {} python -m unittest {}
#              "
#          done

  build-wheel-macos:
    name: Build macos wheels
    runs-on: macos-14

    steps:
      - name: try to restore the macos wheels cache
        id: restore_macos_wheels
        uses: actions/cache/restore@v4
        with:
          key: macos-wheels-${{ hashFiles('.github/workflows/build-wheels.yaml', '.github/actions/**', 'src/**', 'genome_kit/**', 'pyproject.toml', 'setup.py', 'setup/**') }}
          path: dist

      # skip remaining steps on cache hit

      - if: ${{ steps.restore_macos_wheels.outputs.cache-hit != 'true' }}
        uses: actions/checkout@v4

      - if: ${{ steps.restore_macos_wheels.outputs.cache-hit != 'true' }}
        name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - if: ${{ steps.restore_macos_wheels.outputs.cache-hit != 'true' }}
        name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.23.3

      - if: ${{ steps.restore_macos_wheels.outputs.cache-hit != 'true' }}
        name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse && ls -l wheelhouse/
        env:
          GK_BUILD_WHEELS: "1"
          CIBW_ARCHS_MACOS: x86_64 arm64
          CIBW_BUILD: "cp310-*"
#          CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"

      - if: ${{ steps.restore_macos_wheels.outputs.cache-hit != 'true' }}
        name: cache mamba env
        id: save_mamba_cache
        uses: actions/cache/save@v4
        with:
          key: macos-wheels-${{ hashFiles('.github/workflows/build-wheels.yaml', '.github/actions/**', 'src/**', 'genome_kit/**', 'pyproject.toml', 'setup.py', 'setup/**') }}
          path: wheelhouse/*.whl


  test-wheel-macos:
    needs: build-wheel-macos
    name: Test wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # macos-14 == arm64, macos-13 == x86_64
#          - {"os": "macos-14", "arch": "arm64", "pyver": "3.9", "pyvershort": "39"}
          - {"os": "macos-14", "arch": "arm64", "pyver": "3.10", "pyvershort": "310"}
#          - {"os": "macos-14", "arch": "arm64", "pyver": "3.11", "pyvershort": "311"}
#          - {"os": "macos-14", "arch": "arm64", "pyver": "3.12", "pyvershort": "312"}
#          - {"os": "macos-13", "arch": "x86_64", "pyver": "3.9", "pyvershort": "39"}
          - {"os": "macos-13", "arch": "x86_64", "pyver": "3.10", "pyvershort": "310"}
#          - {"os": "macos-13", "arch": "x86_64", "pyver": "3.11", "pyvershort": "311"}
#          - {"os": "macos-13", "arch": "x86_64", "pyver": "3.12", "pyvershort": "312"}

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.pyver }}

      - name: Download built wheels
        uses: actions/cache/restore@v4
        with:
          key: macos-wheels-${{ hashFiles('.github/workflows/build-wheels.yaml', '.github/actions/**', 'src/**', 'genome_kit/**', 'pyproject.toml', 'setup.py', 'setup/**') }}
          path: ./dist
          fail-on-cache-miss: true

      - name: Verify GK module loads
        run: |
          set -euxo pipefail
          ls -l ./dist/
          ls -l ./dist/*cp${{ matrix.pyvershort }}*${{ matrix.arch }}.whl
          pip install ./dist/*cp${{ matrix.pyvershort }}*${{ matrix.arch }}.whl
          python -c 'import genome_kit; print(genome_kit.__version__)'

      - uses: actions/checkout@v4

      - name: Run unit tests
        run: |
          set -euxo pipefail
          mv tests /tmp/
          pushd /tmp
          ls tests/test_*.py | sed 's/\.py$//' | sed 's/tests\//tests./' | CI=1 xargs --verbose -I {} python -m unittest {}


#  publish-to-pypi:
#    needs: [build-wheel-linux, test-wheel-macos]