name: run-unit-tests
run-name: run unit tests
on:
  push:
    # TODO remove before merging (ignore release-please branches)
    branches: [chore/setup-ci]
  pull_request: {}

jobs:
  build-linux:
    # TODO need large?
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: get meta.yaml from conda-forge
        shell: bash -l -e {0}
        run: |
          set -x
          mkdir -p conda-recipe
          curl -s -L -o conda-recipe/meta.yaml https://raw.githubusercontent.com/conda-forge/genomekit-feedstock/main/recipe/meta.yaml
          set +x

      - name: restore mamba env
        id: save_mamba_cache
        uses: actions/cache@v4
        with:
          key: mamba-env-${{ runner.arch }}-${{ hashFiles('.github/workflows/run-tests.yaml') }}-${{ hashFiles('conda-recipe/meta.yaml') }}
          # TODO: need this? see https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#using-the-cache-action
#          restore-keys: |
#            mamba-env-${{ runner.arch }}-${{ hashFiles('.circleci/config.yml') }}-
#            mamba-env-${{ runner.arch }}-
#            mamba-env-$-
          path: |
            ${HOME}/micromamba
            ${HOME}/.condarc
            ${HOME}/bin/micromamba

      - if: ${{ steps.save_mamba_cache.outputs.cache-hit != 'true' }}
        uses: ./.github/actions/install-mamba
        with:
          installer-url: https://micro.mamba.pm/api/micromamba/linux-64/1.5.7

      - if: ${{ steps.save_mamba_cache.outputs.cache-hit != 'true' }}
        uses: ./.github/actions/create-conda-env

      - name: create build env
        shell: bash -l -e {0}
        run: |
          set -x
          if [ ! -d "${HOME}/micromamba/envs/build" ]; then
            micromamba create -yqn build -c conda-forge \
              boa==0.16.0 mamba==1.5.7 conda==24.1.2 \
              ccache
          fi
          set +x

      - if: ${{ steps.save_mamba_cache.outputs.cache-hit != 'true' }}
        uses: ./.github/actions/configure-conda
        with:
          env: build

      - name: restore mamba gk ccache
        id: save_mamba_gk_ccache
        uses: actions/cache@v4
        with:
          key: gk-mamba-ccache-${{ runner.arch }}-${{ github.head_ref || github.ref_name }}-${{ github.sha }}
          path: |
            ${HOME}/.ccache

      - name: set compiler cache size
        shell: bash -l -e {0}
        run: |
          set -x
          micromamba activate build
          ccache -M 100M
          set +x

      - name: build conda package
        shell: bash -l -e {0}
        run: |
          set -x
          micromamba activate build
          mkdir ~/conda-bld
          conda mambabuild --croot ~/conda-bld -q --no-test conda-recipe
          conda build --croot ~/conda-bld purge
          conda clean -it
          set +x
